import "@/modules/notebook/load-test-env";

import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { YoutubeTranscriptNotAvailableError } from "youtube-transcript";
import { prisma } from "@/lib/db";
import { createConversationForUser } from "@/modules/conversation/create-conversation";
import { createNotebookForUser } from "@/modules/notebook/service";
import { countSourceChunks } from "@/modules/rag/index-source";
import { retrieveRelevantChunks } from "@/modules/rag/retrieve";
import { youtubeTranscriptClient } from "@/modules/source/fetch-youtube";
import {
  createIndexedSourceFromUpload,
  createIndexedSourceFromWebsite,
  createIndexedSourceFromYoutube,
  createSourceFromUpload,
  deleteSourceForUser,
} from "@/modules/source/service";

const hasDatabase = Boolean(process.env.DATABASE_URL?.trim());
const hasOpenAI = Boolean(process.env.OPENAI_API_KEY?.trim());

const VIDEO_ID = "dQw4w9WgXcQ";

const ROMAN_VTT = `WEBVTT
Kind: captions
Language: en

NOTE Generated by the lecture capture system.

STYLE
::cue { color: white }

1
00:00:01.000 --> 00:00:06.000 align:start
The Roman aqueducts carried fresh water into the city across stone arches.

2
00:00:06.000 --> 00:00:12.000
<v Lecturer>Engineers used a steady <b>gradient</b> so gravity moved the water.</v>

3
00:00:12.000 --> 00:00:19.000
Roman concrete and arch construction made these aqueduct spans durable for centuries.
`;

function vttFile(contents: string, filename = "roman-aqueducts.en.vtt") {
  return new File([contents], filename, { type: "text/vtt" });
}

describe("vtt source indexing", { skip: !hasDatabase || !hasOpenAI }, () => {
  let userId = "";
  let notebookId = "";
  const originalFetch = globalThis.fetch;
  const originalTranscript = youtubeTranscriptClient.fetchTranscript;

  before(async () => {
    const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const user = await prisma.user.create({
      data: {
        clerkId: `test_vtt_${suffix}`,
        email: `vtt-${suffix}@example.com`,
      },
    });
    userId = user.id;
    const notebook = await createNotebookForUser({
      userId,
      title: "VTT Sources",
    });
    notebookId = notebook.id;

    youtubeTranscriptClient.fetchTranscript = async (videoId) => {
      if (videoId !== VIDEO_ID) {
        throw new YoutubeTranscriptNotAvailableError(videoId);
      }
      return [
        {
          text: "Quantum entanglement links particle pairs so measuring one instantly affects the other.",
          duration: 5000,
          offset: 0,
        },
        {
          text: "This lecture covers entanglement experiments and quantum physics for students.",
          duration: 5000,
          offset: 5000,
        },
      ];
    };

    globalThis.fetch = (async (
      input: RequestInfo | URL,
      init?: RequestInit
    ) => {
      const url = String(
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url
      );

      if (url.includes("youtube.com/oembed")) {
        return Response.json({
          title: "Quantum Entanglement Lecture",
          author_name: "Physics Channel",
          thumbnail_url: `https://i.ytimg.com/vi/${VIDEO_ID}/hqdefault.jpg`,
        });
      }

      if (url.includes("mars.example")) {
        return new Response(
          `<!doctype html><html><head><title>Mars Rovers</title></head>
           <body><article><h1>Mars Rovers</h1>
           <p>The Perseverance rover explores Jezero Crater on Mars collecting rock cores.
           Its instruments study martian geology and search for ancient microbial biosignatures.
           This article covers Mars exploration and rover missions for notebook RAG tests.</p>
           </article></body></html>`,
          { status: 200, headers: { "content-type": "text/html" } }
        );
      }

      return originalFetch(input, init);
    }) as typeof fetch;
  });

  after(async () => {
    youtubeTranscriptClient.fetchTranscript = originalTranscript;
    globalThis.fetch = originalFetch;
    if (userId) {
      await prisma.user.delete({ where: { id: userId } });
    }
  });

  it("indexes a VTT subtitle file into retrievable chunks", async () => {
    const source = await createIndexedSourceFromUpload({
      userId,
      notebookId,
      file: vttFile(ROMAN_VTT),
    });

    assert.equal(source.type, "VTT");
    assert.equal(source.indexingStatus, "INDEXED");
    assert.equal(source.mimeType, "text/vtt");
    assert.equal(source.title, "roman-aqueducts");
    assert.equal(source.metadata?.cueCount, 3);
    assert.equal(source.metadata?.language, "en");
    assert.equal(source.metadata?.durationSeconds, 19);

    // Stored text is the clean transcript, not the raw subtitle file.
    const text = source.extractedText ?? "";
    assert.match(text, /Roman aqueducts carried fresh water/);
    assert.match(text, /Engineers used a steady gradient/);
    assert.doesNotMatch(text, /-->/);
    assert.doesNotMatch(text, /WEBVTT|Kind:|NOTE|STYLE/);
    assert.doesNotMatch(text, /<[^>]+>/);

    assert.ok((await countSourceChunks(source.id)) > 0);

    await deleteSourceForUser({ userId, sourceId: source.id });
  });

  it("rejects invalid, empty, and corrupted VTT files", async () => {
    await assert.rejects(
      () =>
        createSourceFromUpload({
          userId,
          notebookId,
          file: vttFile(
            "1\n00:00:01,000 --> 00:00:04,000\nThis is SRT, not VTT.\n",
            "subtitles.vtt"
          ),
        }),
      /Invalid VTT file: missing WEBVTT header/
    );

    await assert.rejects(
      () =>
        createSourceFromUpload({
          userId,
          notebookId,
          file: vttFile("WEBVTT\nKind: captions\n", "header-only.vtt"),
        }),
      /Invalid VTT file: no subtitle cues found/
    );

    await assert.rejects(
      () =>
        createSourceFromUpload({
          userId,
          notebookId,
          file: vttFile(
            "WEBVTT\n\n00:00:01.000 --> 00:00:04.000\n\u0000\u0000\u0000\u0000",
            "corrupt.vtt"
          ),
        }),
      /Corrupted VTT file/
    );

    // Failed parses must not leave Source rows behind.
    const leftovers = await prisma.source.count({
      where: { notebookId, type: "VTT" },
    });
    assert.equal(leftovers, 0);
  });

  it("rejects a duplicate subtitle upload in the same notebook", async () => {
    const first = await createSourceFromUpload({
      userId,
      notebookId,
      file: vttFile(ROMAN_VTT),
    });

    await assert.rejects(
      () =>
        createSourceFromUpload({
          userId,
          notebookId,
          file: vttFile(ROMAN_VTT),
        }),
      /already added to the notebook/
    );

    await deleteSourceForUser({ userId, sourceId: first.id });
  });

  it("mixed notebook: pdf + website + youtube + vtt all retrievable", async () => {
    // Minimal PDF with an extractable text layer.
    const pdfBytes = Buffer.from(
      `%PDF-1.1
1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj
2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj
3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 144] /Contents 4 0 R /Resources<< /Font<< /F1 5 0 R >> >> >>endobj
4 0 obj<< /Length 74 >>stream
BT /F1 12 Tf 20 100 Td (Sicilian Defense chess opening pawn structure) Tj ET
endstream
endobj
5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj
xref
0 6
0000000000 65535 f 
trailer<< /Size 6 /Root 1 0 R >>
startxref
448
%%EOF`
    );

    const pdfSource = await createIndexedSourceFromUpload({
      userId,
      notebookId,
      file: new File([pdfBytes], "chess.pdf", { type: "application/pdf" }),
    });

    const webSource = await createIndexedSourceFromWebsite({
      userId,
      notebookId,
      url: "https://mars.example/rovers",
    });

    const ytSource = await createIndexedSourceFromYoutube({
      userId,
      notebookId,
      url: `https://www.youtube.com/watch?v=${VIDEO_ID}`,
    });

    const vttSource = await createIndexedSourceFromUpload({
      userId,
      notebookId,
      file: vttFile(ROMAN_VTT),
    });

    const conversation = await createConversationForUser({
      userId,
      notebookId,
    });

    async function search(query: string) {
      return retrieveRelevantChunks({
        conversationId: conversation.id,
        notebookId,
        query,
        limit: 6,
      });
    }

    const aqueducts = await search("Roman aqueduct water gradient arches");
    const mars = await search("Perseverance rover Jezero Crater Mars");
    const quantum = await search("quantum entanglement particles");
    const chess = await search("Sicilian Defense chess opening");

    assert.ok(
      aqueducts.some((chunk) => chunk.sourceId === vttSource.id),
      "VTT source should answer aqueduct questions"
    );
    assert.ok(
      mars.some((chunk) => chunk.sourceId === webSource.id),
      "Website source should answer Mars questions"
    );
    assert.ok(
      quantum.some((chunk) => chunk.sourceId === ytSource.id),
      "YouTube source should answer quantum questions"
    );
    assert.ok(
      chess.some((chunk) => chunk.sourceId === pdfSource.id),
      "PDF source should answer chess questions"
    );

    await deleteSourceForUser({ userId, sourceId: pdfSource.id });
    await deleteSourceForUser({ userId, sourceId: webSource.id });
    await deleteSourceForUser({ userId, sourceId: ytSource.id });
    await deleteSourceForUser({ userId, sourceId: vttSource.id });
  });
});
